name: RISC-V

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-sp1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install toolchain
      run: |
        curl -L https://sp1up.succinct.xyz | bash
        /home/runner/.sp1/bin/sp1up
        rustup default succinct

    - name: Build SP1
      run: cargo build --target=riscv32im-succinct-zkvm-elf -p ream-consensus -p ream-bls

  build-risc0:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install toolchain
      run: |
        curl -L https://risczero.com/install | bash
        /home/runner/.risc0/bin/rzup install
        cargo risczero install
        rustup default risc0
        
    - name: Build Risc0
      run: cargo build --target=riscv32im-risc0-zkvm-elf -p ream-consensus -p ream-bls

